(() => {
  "use strict";

  // ---- State -----------------------------------------------------------
  let parts = [];        // full catalog from the uploaded sheet
  let locations = [];    // distinct store locations, used as the sidebar filter
  let quantities = {};   // sku -> qty the user wants to add on top of what's needed
  let onHand = {};       // sku -> user-entered current on-hand count (overrides the sheet value)
  let excluded = new Set(); // skus explicitly removed from the ticket, even if a shortfall would otherwise add them back
  let activeLocation = "all";
  let query = "";
  
  // ---- Elements ----------------------------------------------------------
  const statusScreen = document.getElementById("statusScreen");
  const statusTitle = document.getElementById("statusTitle");
  const statusHint = document.getElementById("statusHint");
  const mainLayout = document.getElementById("mainLayout");
  const uploadError = document.getElementById("uploadError");
  const retryBtn = document.getElementById("retryBtn");
  const searchWrap = document.getElementById("searchWrap");
  const searchInput = document.getElementById("searchInput");
  const sidebar = document.getElementById("sidebar");
  const partsGrid = document.getElementById("partsGrid");
  const ticketLines = document.getElementById("ticketLines");
  const lineCountEl = document.getElementById("lineCount");
  const totalUnitsEl = document.getElementById("totalUnits");
  const exportBtn = document.getElementById("exportBtn");
  const clearBtn = document.getElementById("clearBtn");
  const exportConfirm = document.getElementById("exportConfirm");
  const reloadBtn = document.getElementById("reloadBtn");
  const emailToInput = document.getElementById("emailTo");
  const emailListEl = document.getElementById("emailList");
  const emailBtn = document.getElementById("emailBtn");
  const historyDay = document.getElementById("historyDay");
  const historyWeek = document.getElementById("historyWeek");
  const historyMonth = document.getElementById("historyMonth");
  const modalTitle = document.getElementById("modalTitle");
  const modalText = document.getElementById("modalText");
  let pendingOrderNo = null; // filled in by fetchOrderNo() below
  let pendingAction = "export"; // "export" or "email" — which the confirm modal is for

  document.getElementById("ticketDate").textContent = todayStamp();

  // ---- Email availability -----------------------------------------------
  // Outlook sending only works when THIS SERVER runs on a Windows machine
  // with Outlook desktop + pywin32 (i.e. the laptop). The button always
  // shows; if the server can't send (e.g. hosted on Render/Linux), clicking
  // it explains why instead of silently hiding.
  let outlookAvailable = false;
  async function fetchEmailStatus() {
    try {
      const res = await fetch("/api/email-status");
      const data = await res.json();
      outlookAvailable = !!data.available;
    } catch (err) {
      outlookAvailable = false;
    }
  }
  fetchEmailStatus();

  // ---- Email autofill ----------------------------------------------------
  // Pull the saved address list (EMAIL_ADDRESSES in app.py) into the
  // <datalist> behind the "Email to" box, so typing offers suggestions.
  async function fetchEmails() {
    try {
      const res = await fetch("/api/emails");
      const data = await res.json();
      emailListEl.innerHTML = "";
      (data.emails || []).forEach((addr) => {
        const opt = document.createElement("option");
        opt.value = addr;
        emailListEl.appendChild(opt);
      });
    } catch (err) {
      // Non-critical — autofill just won't offer suggestions.
    }
  }
  fetchEmails();

  // ---- Order numbering (server-side, not localStorage) ------------------
  // The PO number is generated by the Flask backend from a small history
  // file it keeps next to itself, so it stays correct and sequential no
  // matter which browser or machine you're using — localStorage was only
  // ever visible to one browser on one computer.
  async function fetchOrderNo() {
    try {
      const res = await fetch("/api/order-no");
      const data = await res.json();
      pendingOrderNo = data.order_no;
      document.getElementById("orderNo").textContent = pendingOrderNo;
      document.getElementById("ticketOrderNo").textContent = pendingOrderNo;
    } catch (err) {
      pendingOrderNo = "PO-unknown";
      document.getElementById("orderNo").textContent = pendingOrderNo;
      document.getElementById("ticketOrderNo").textContent = pendingOrderNo;
    }
  }

  async function fetchOrderSummary() {
    try {
      const res = await fetch("/api/order-summary");
      const data = await res.json();
      renderHistory(data);
    } catch (err) {
      // Non-critical — just leave the dashes in place.
    }
  }

  function renderHistory(data) {
    const fmt = (w) => `${w.total_units} units \u00b7 ${w.distinct_parts} parts \u00b7 ${w.orders} orders`;
    if (data.day) historyDay.textContent = fmt(data.day);
    if (data.week) historyWeek.textContent = fmt(data.week);
    if (data.month) historyMonth.textContent = fmt(data.month);
  }

  fetchOrderNo();
  fetchOrderSummary();

  // ---- Shared draft (persists across refreshes AND devices) -------------
  // Every edit is saved (debounced) to the server's draft.json; every page
  // load restores it; and open pages poll every few seconds so an order
  // started on the laptop shows up on the phone and vice versa.
  let draftRev = 0;       // last server revision we've seen/produced
  let draftDirty = false; // local edits not yet saved to the server
  let saveTimer = null;

  function draftState() {
    return {
      quantities,
      onHand,
      excluded: Array.from(excluded),
      email: emailToInput.value,
    };
  }

  function scheduleSaveDraft() {
    draftDirty = true;
    clearTimeout(saveTimer);
    saveTimer = setTimeout(saveDraftNow, 400);
  }

  async function saveDraftNow() {
    try {
      const res = await fetch("/api/draft", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state: draftState() }),
      });
      const data = await res.json();
      if (data && typeof data.rev === "number") {
        draftRev = data.rev;
        draftDirty = false;
      }
    } catch (err) {
      // Server unreachable — stay dirty; next edit or poll cycle retries.
    }
  }

  function applyDraft(state) {
    state = state || {};
    quantities = state.quantities || {};
    onHand = state.onHand || {};
    excluded = new Set(state.excluded || []);
    if (typeof state.email === "string" && document.activeElement !== emailToInput) {
      emailToInput.value = state.email;
    }
    renderParts();
    renderTicket();
  }

  async function loadDraft() {
    try {
      const res = await fetch("/api/draft");
      const data = await res.json();
      draftRev = data.rev || 0;
      return data.state || {};
    } catch (err) {
      return {};
    }
  }

  // ---- Real-time sync (Socket.IO — same engine as the dispatch system) --
  // The server pushes every draft change and every recorded order to all
  // connected devices instantly, so laptop and phone mirror each other.
  function maybeApplyRemote(data) {
    if (!data || typeof data.rev !== "number") return;
    if (data.rev === draftRev) return;   // already have this state
    if (draftDirty) return;              // our own unsaved edits win
    const el = document.activeElement;
    if (el && (el.tagName === "INPUT" || el.tagName === "TEXTAREA")) return;
    draftRev = data.rev;
    applyDraft(data.state);
  }

  try {
    const socket = io({ transports: ["polling", "websocket"] });
    socket.on("draft_update", maybeApplyRemote);
    socket.on("history_update", () => {
      fetchOrderNo();
      fetchOrderSummary();
    });
  } catch (err) {
    // Socket library didn't load — the reconcile poll below still syncs.
  }

  // Slow catch-up poll: covers reconnects or any missed push.
  setInterval(async () => {
    if (draftDirty) return;
    const el = document.activeElement;
    if (el && (el.tagName === "INPUT" || el.tagName === "TEXTAREA")) return;
    try {
      const res = await fetch("/api/draft");
      maybeApplyRemote(await res.json());
    } catch (err) {
      // Offline blip — try again next cycle.
    }
  }, 10000);

  // ---- Loading from the local file -----------------------------------
  reloadBtn.addEventListener("click", () => loadParts(true));
  retryBtn.addEventListener("click", () => loadParts(false));

  function showError(msg) {
    uploadError.textContent = msg;
    uploadError.hidden = false;
    retryBtn.hidden = false;
    statusTitle.textContent = "Couldn't load parts";
    statusHint.hidden = true;
  }
  function hideError() {
    uploadError.hidden = true;
    retryBtn.hidden = true;
  }

  async function loadParts(fromReloadButton) {
    hideError();
    if (fromReloadButton) {
      mainLayout.hidden = true;
      statusScreen.hidden = false;
    }
    statusTitle.textContent = "Loading parts\u2026";
    statusHint.hidden = false;

    try {
      const res = await fetch("/api/parts");
      const data = await res.json();

      if (!res.ok) {
        showError(data.error || "Something went wrong reading the file.");
        return;
      }

      parts = data.parts;
      locations = data.locations;

      // Restore the shared draft (saved server-side) so a refresh or a
      // different device picks up right where the order left off.
      const saved = await loadDraft();
      if (saved && (saved.quantities || saved.onHand || saved.excluded || saved.email)) {
        quantities = saved.quantities || {};
        onHand = saved.onHand || {};
        excluded = new Set(saved.excluded || []);
        if (typeof saved.email === "string" && saved.email) emailToInput.value = saved.email;
      }

      // keep existing quantities/on-hand entries where the SKU still exists, drop the rest
      const keptQuantities = {};
      const keptOnHand = {};
      for (const p of parts) {
        if (quantities[p.sku]) keptQuantities[p.sku] = quantities[p.sku];
        if (onHand[p.sku] !== undefined) keptOnHand[p.sku] = onHand[p.sku];
      }
      quantities = keptQuantities;
      onHand = keptOnHand;
      if (!locations.includes(activeLocation)) activeLocation = "all";

      renderSidebar();
      renderParts();
      renderTicket();

      statusScreen.hidden = true;
      mainLayout.hidden = false;
      searchWrap.hidden = false;
    } catch (err) {
      showError("Couldn't reach the server. Is the Flask app running?");
    }
  }

  // Kick off the initial load as soon as the page opens.
  loadParts(false);

  // ---- Sidebar (store locations) --------------------------------------
  function renderSidebar() {
    sidebar.innerHTML = "";
    sidebar.appendChild(
      catButton("All Parts", "all", activeLocation === "all")
    );
    locations.forEach((loc) => {
      sidebar.appendChild(catButton(loc, loc, activeLocation === loc));
    });
  }

  function catButton(label, value, active) {
    const btn = document.createElement("button");
    btn.className = "cat-btn cond" + (active ? " active" : "");
    btn.textContent = label;
    btn.addEventListener("click", () => {
      activeLocation = value;
      renderSidebar();
      renderParts();
    });
    return btn;
  }

  // ---- Search -----------------------------------------------------------
  searchInput.addEventListener("input", () => {
    query = searchInput.value;
    renderParts();
  });

  // ---- Parts grid ---------------------------------------------------------
  function filteredParts() {
    const q = query.trim().toLowerCase();
    return parts.filter((p) => {
      const matchesLocation = activeLocation === "all" || p.location === activeLocation;
      const matchesQuery =
        !q ||
        p.description.toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q);
      return matchesLocation && matchesQuery;
    });
  }

  function renderParts() {
    partsGrid.innerHTML = "";
    const list = filteredParts();

    if (list.length === 0) {
      const empty = document.createElement("div");
      empty.className = "empty-state";
      empty.textContent = query
        ? `No parts match "${query}".`
        : "No parts in this location.";
      partsGrid.appendChild(empty);
      return;
    }

    list.forEach((p) => partsGrid.appendChild(partCard(p)));
  }

  // ---- Order-quantity math ------------------------------------------
  // "On hand" is entirely user-entered — it does NOT get pre-filled from
  // the sheet, since that data can be stale. Until someone types a count
  // in, it's treated as 0 (i.e. "not yet counted"), which is the safest
  // default because it surfaces the full shortfall rather than hiding it.
  function getOnHand(p) {
    return onHand[p.sku] !== undefined ? onHand[p.sku] : 0;
  }
  // Containers needed to top up to one 16h container-usage's worth.
  function neededQty(p) {
    const raw = (p.usage_16h || 0) - getOnHand(p);
    return raw > 0 ? Math.ceil(raw) : 0;
  }
  // What actually goes on the order: whatever quantity the user added by
  // hand, plus the shortfall between usage/16h and on-hand.
  function exportQty(p) {
    if (excluded.has(p.sku)) return 0;
    return (quantities[p.sku] || 0) + neededQty(p);
  }

  function partCard(p) {
    const card = document.createElement("div");
    card.className = "part-card";

    const qty = quantities[p.sku] || 0;
    const onHandEntered = onHand[p.sku]; // undefined until the user actually types a value
    const usage = p.usage_16h || 0;
    const usageToAdd = Math.ceil(usage); // round up — can't order part of a container

    card.innerHTML = `
      <div>
        <div class="part-name">${escapeHtml(p.description || "(no description)")}</div>
        <div class="part-meta mono">${escapeHtml(p.sku)} &middot; ${escapeHtml(p.location)}${p.extra_field ? ` (${escapeHtml(p.extra_field)})` : ""}</div>
        <div class="part-stats mono">Quantity: ${formatNum(p.qty_on_hand)} &middot; Container Usage/16h: ${formatNum(p.usage_16h)}</div>
      </div>
      <div class="onhand-row">
        <label class="onhand-label mono">On hand now</label>
        <input type="text" inputmode="numeric" class="mono onhand-input" placeholder="0" value="${onHandEntered !== undefined ? onHandEntered : ""}" />
        <span class="need-badge mono" data-need></span>
      </div>
      <div class="qty-row">
        <div class="stepper">
          <button type="button" data-action="dec" aria-label="Decrease quantity">−</button>
          <input type="text" inputmode="numeric" class="mono qty-input" value="${qty}" />
          <button type="button" data-action="inc" aria-label="Increase quantity">+</button>
        </div>
        <button type="button" class="add-usage-btn mono" data-action="add-usage" ${usageToAdd <= 0 ? "disabled" : ""}>
          +${usageToAdd} (16h)
        </button>
      </div>
    `;

    const input = card.querySelector(".qty-input");
    const onHandInput = card.querySelector(".onhand-input");
    const needBadge = card.querySelector("[data-need]");

    function refreshNeedBadge() {
      const need = neededQty(p);
      needBadge.textContent = need > 0 ? `Need +${formatNum(need)}` : "Stocked";
      needBadge.classList.toggle("need-short", need > 0);
    }
    refreshNeedBadge();

    card.querySelector('[data-action="dec"]').addEventListener("click", () => {
      setQty(p.sku, (quantities[p.sku] || 0) - 1);
      input.value = quantities[p.sku] || 0;
    });
    card.querySelector('[data-action="inc"]').addEventListener("click", () => {
      setQty(p.sku, (quantities[p.sku] || 0) + 1);
      input.value = quantities[p.sku] || 0;
    });
    input.addEventListener("change", () => {
      const val = parseInt(input.value, 10);
      setQty(p.sku, isNaN(val) ? 0 : val);
      input.value = quantities[p.sku] || 0;
    });
    onHandInput.addEventListener("change", () => {
      const val = parseInt(onHandInput.value, 10);
      onHand[p.sku] = isNaN(val) ? 0 : Math.max(0, val);
      onHandInput.value = onHand[p.sku];
      excluded.delete(p.sku); // editing on-hand means they want it recalculated, not hidden
      refreshNeedBadge();
      renderTicket();
      scheduleSaveDraft();
    });
    // Adds the container-usage-per-16h amount straight onto the current
    // quantity in one click, without submitting anything — you can still
    // adjust it afterwards with the stepper or by typing. Note this is
    // separate from the automatic "Need" shortfall below, which gets
    // added on top at export time regardless.
    card.querySelector('[data-action="add-usage"]').addEventListener("click", () => {
      setQty(p.sku, (quantities[p.sku] || 0) + usageToAdd);
      input.value = quantities[p.sku] || 0;
    });

    return card;
  }

  function setQty(sku, qty) {
    quantities[sku] = Math.max(0, qty);
    if (quantities[sku] > 0) excluded.delete(sku);
    renderTicket();
    scheduleSaveDraft();
  }

  // ---- Pick ticket -----------------------------------------------------
  function orderLines() {
    return parts
      .filter((p) => exportQty(p) > 0)
      .map((p) => ({ ...p, qty: exportQty(p), rawQty: quantities[p.sku] || 0, need: neededQty(p) }));
  }

  function renderTicket() {
    const lines = orderLines();
    ticketLines.innerHTML = "";

    if (lines.length === 0) {
      const empty = document.createElement("div");
      empty.className = "ticket-empty";
      empty.textContent = "No parts selected yet. Add quantities to build the order.";
      ticketLines.appendChild(empty);
    } else {
      lines.forEach((l) => {
        const row = document.createElement("div");
        row.className = "ticket-line";
        const breakdown = l.need > 0
          ? `<div class="ticket-line-breakdown mono">${l.rawQty} added + ${formatNum(l.need)} need</div>`
          : "";
        row.innerHTML = `
          <div style="min-width:0;">
            <div class="ticket-line-name">${escapeHtml(l.description || l.sku)}</div>
            <div class="ticket-line-sku mono">${escapeHtml(l.sku)}</div>
            ${breakdown}
          </div>
          <div class="ticket-line-right">
            <span class="ticket-line-qty mono">&times;${formatNum(l.qty)}</span>
            <button class="remove-btn" aria-label="Remove ${escapeHtml(l.sku)}">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>
            </button>
          </div>
        `;
        row.querySelector(".remove-btn").addEventListener("click", () => {
          setQty(l.sku, 0);
          excluded.add(l.sku);
          renderParts();
          renderTicket();
          scheduleSaveDraft();
        });
        ticketLines.appendChild(row);
      });
    }

    const totalUnits = lines.reduce((sum, l) => sum + l.qty, 0);
    lineCountEl.textContent = lines.length;
    totalUnitsEl.textContent = totalUnits;
    exportBtn.disabled = lines.length === 0;
    emailBtn.disabled = lines.length === 0 || !emailToInput.value.trim();
    clearBtn.hidden = lines.length === 0;
    exportConfirm.hidden = true;
  }

  emailToInput.addEventListener("input", () => {
    emailBtn.disabled = orderLines().length === 0 || !emailToInput.value.trim();
    scheduleSaveDraft();
  });

  clearBtn.addEventListener("click", () => {
    quantities = {};
    onHand = {};
    excluded = new Set();
    renderParts();
    renderTicket();
    scheduleSaveDraft();
  });

  // ---- Export / Email -----------------------------------------------------

  exportBtn.addEventListener("click", () => {
    if (orderLines().length === 0) return;
    pendingAction = "export";
    modalTitle.textContent = "Confirm Export";
    modalText.textContent = "Are you sure you want to export this order?";
    document.getElementById("modalOrderNo").textContent = pendingOrderNo;
    modalConfirm.textContent = "Export";
    confirmModal.hidden = false;
  });

  emailBtn.addEventListener("click", () => {
    if (orderLines().length === 0 || !emailToInput.value.trim()) return;
    if (!outlookAvailable) {
      alert(
        "Send via Outlook only works when this app is running on the Windows " +
        "laptop (Outlook desktop + pywin32 installed). This copy is running on " +
        "a server without Outlook — use Export to Excel and attach the file to " +
        "an email instead."
      );
      return;
    }
    pendingAction = "email";
    modalTitle.textContent = "Confirm Send";
    modalText.textContent = `Send this order to ${emailToInput.value.trim()}?`;
    document.getElementById("modalOrderNo").textContent = pendingOrderNo;
    modalConfirm.textContent = "Send";
    confirmModal.hidden = false;
  });

  modalCancel.addEventListener("click", () => {
    confirmModal.hidden = true;
  });

  modalConfirm.addEventListener("click", async () => {
    confirmModal.hidden = true;
    if (pendingAction === "email") {
      await doEmailExport();
    } else {
      await doDownloadExport();
    }
    // Pull the next order number and refresh the history stats now that
    // this export has been recorded server-side.
    fetchOrderNo();
    fetchOrderSummary();
  });

  async function doDownloadExport() {
    const orderNo = pendingOrderNo;
    const lines = orderLines().map(l => ({ sku: l.sku, qty: l.qty }));

    exportBtn.disabled = true;
    const originalText = exportBtn.innerHTML;
    exportBtn.textContent = "Exporting…";

    try {
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ lines, order_no: orderNo }),
      });

      if (!res.ok) {
        alert("Export failed.");
        return;
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${orderNo}.xlsx`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);

      exportConfirm.textContent = `Downloaded ${orderNo}.xlsx`;
      exportConfirm.hidden = false;
    } finally {
      exportBtn.innerHTML = originalText;
      exportBtn.disabled = orderLines().length === 0;
    }
  }

  async function doEmailExport() {
    const orderNo = pendingOrderNo;
    const email = emailToInput.value.trim();
    const lines = orderLines().map(l => ({ sku: l.sku, qty: l.qty }));

    emailBtn.disabled = true;
    const originalText = emailBtn.innerHTML;
    emailBtn.textContent = "Sending…";

    try {
      const res = await fetch("/api/export-email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ lines, order_no: orderNo, email }),
      });

      // The error body should be JSON, but a gateway timeout (Render 502)
      // or auth page returns HTML — parse defensively so we can still show
      // a real status code instead of a misleading "couldn't reach" alert.
      let data = null;
      try { data = await res.json(); } catch (e) { /* non-JSON body */ }

      if (!res.ok) {
        alert(
          (data && data.error) ||
          `Sending failed — the server responded with status ${res.status}. ` +
          `Check the Render logs (Dashboard → your service → Logs) for the full error.`
        );
        return;
      }

      exportConfirm.textContent = `Sent ${orderNo}.xlsx to ${(data && data.email) || email}`;
      exportConfirm.hidden = false;
    } catch (err) {
      alert("Couldn't reach the server to send the email.");
    } finally {
      emailBtn.innerHTML = originalText;
      emailBtn.disabled = orderLines().length === 0 || !emailToInput.value.trim();
    }
  }

  // ---- Helpers -----------------------------------------------------------
  function todayStamp() {
    const d = new Date();
    return d.toLocaleDateString("en-US", { year: "numeric", month: "2-digit", day: "2-digit" });
  }

  function formatNum(n) {
    if (n === null || n === undefined) return "0";
    return Number.isInteger(n) ? n : n.toFixed(1);
  }
  function escapeHtml(str) {
    const div = document.createElement("div");
    div.textContent = str ?? "";
    return div.innerHTML;
  }
})();
